#-*- coding: utf-8 -*-

{
	"name": "Akademik Inherited",
	"version": "1.0", 
	"depends": [
		'base','account','hr',
		'vit_akademik'
	],
	"author": "Akhmad D. Sembiring [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Akademik module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"view/partner.xml",
		"view/mahasiswa.xml",
		# "view/mata_kuliah.xml",
		"view/fakultas.xml",
		"view/prodi.xml",
		# "view/kurikulum.xml",
		# "view/tahun_ajaran.xml",
		"view/dosen.xml",
		# "view/semester.xml",
		"view/perguruan_tinggi.xml",
		# "view/jenjang.xml",
		# "view/jabatan_fungsional.xml",
		"view/riwayat_mengajar.xml",
		"view/riwayat_pendidikan.xml",
		# "view/kelas.xml",
		"view/krs.xml",
		# "data/sequence_krs.xml",
		"view/krs_detail.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}