#-*- coding: utf-8 -*-

{
	"name": "Akademik",
	"version": "1.0", 
	"depends": [
		'base','hr','account',
	],
	"author": "Akhmad D. Sembiring [vitraining.com]",
	"category": "Utility",
	"website": "http://vitraining.com",
	"images": ["static/description/images/main_screenshot.jpg"],
	"price": "10",
	"license": "OPL-1",
	"currency": "USD",
	"summary": "This is the Akademik module generated by StarUML Odoo Generator Pro Version",
	"description": """

Information
======================================================================

* created menus
* created objects
* created views
* logics

""",
	"data": [
		"security/groups.xml",
		"security/ir.model.access.csv",
		"view/menu.xml",
		"view/mahasiswa.xml", #inherited
		"view/mata_kuliah.xml",
		"view/fakultas.xml", #inherited
		"view/prodi.xml", #inherited
		"view/kurikulum.xml",
		"view/tahun_ajaran.xml",
		"view/dosen.xml", #inherited
		"view/semester.xml",
		"view/perguruan_tinggi.xml", #inherited
		"view/jenjang.xml",
		"view/jabatan_fungsional.xml",
		"view/riwayat_mengajar.xml",
		"view/riwayat_pendidikan.xml",
		"view/kelas.xml",
		"view/krs.xml",
		"data/sequence_krs.xml",
		"view/krs_detail.xml",
		"view/partner.xml", #inherited
		"view/invoice.xml", #inherited
		"report/mata_kuliah.xml",
		"report/kurikulum.xml",
		"report/tahun_ajaran.xml",
		"report/semester.xml",
		"report/jenjang.xml",
		"report/jabatan_fungsional.xml",
		"report/riwayat_mengajar.xml",
		"report/riwayat_pendidikan.xml",
		"report/kelas.xml",
		"report/krs.xml",
		"report/krs_detail.xml",
	],
	"installable": True,
	"auto_install": False,
	"application": True,
}